--Generated by dbdiagramm.io

CREATE TABLE "category" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "slug" varchar UNIQUE
);

CREATE TABLE "subcategory" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer,
  "name" varchar,
  "slug" varchar UNIQUE
);

CREATE TABLE "product" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer,
  "subcategory_id" integer,
  "name" varchar,
  "manufacturer" varchar,
  "model" varchar,
  "image_url" varchar,
  "product_url" varchar,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "shop" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "base_url" varchar
);

CREATE TABLE "price" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "shop_id" integer,
  "price" float,
  "scraped_at" datetime
);

CREATE TABLE "gpu_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "vram_gb" integer,
  "vram_freq" integer,
  "vram_bandwidth" integer,
  "vram_type" varchar,
  "memory_bus" integer,
  "base_clock_mhz" integer,
  "boost_clock_mhz" integer,
  "tdp_watt" integer,
  "pcie_version" varchar,
  "connectors" varchar,
  "ports" varchar,
  "abmessung" varchar,
  "slots" integer
);

CREATE TABLE "cpu_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "socket" varchar,
  "cores" integer,
  "threads" integer,
  "base_clock_ghz" float,
  "boost_clock_ghz" float,
  "tdp_watt" integer,
  "l3_cache_mb" integer,
  "memory_type" varchar,
  "integrated_graphics" boolean,
  "includes_cooler" boolean
);

CREATE TABLE "mainboard_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "socket" varchar,
  "chipset" varchar,
  "form_factor" varchar,
  "memory_slots" integer,
  "memory_type" varchar,
  "max_memory_gb" integer,
  "pcie5_slots" integer,
  "m2_slots" integer,
  "usb_c_rear" boolean,
  "wifi" boolean,
  "bluetooth" boolean
);

CREATE TABLE "psu_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "watt" integer,
  "efficiency_rating" varchar,
  "modular" varchar,
  "form_factor" varchar,
  "atx3" boolean,
  "pcie16_connectors" integer
);

CREATE TABLE "ram_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "memory_type" varchar,
  "capacity_gb" integer,
  "kit_count" integer,
  "speed_mhz" integer,
  "cl_latency" integer,
  "voltage" float,
  "rgb" boolean
);

CREATE TABLE "storage_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "capacity_gb" integer,
  "interface" varchar,
  "form_factor" varchar,
  "read_mbps" integer,
  "write_mbps" integer,
  "tbw" integer,
  "dram_cache" boolean
);

CREATE TABLE "air_cooler_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "height_mm" integer,
  "tdp_watt" integer,
  "fan_count" integer,
  "fan_size_mm" integer,
  "socket_support" varchar,
  "rgb" boolean
);

CREATE TABLE "case_fan_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "size_mm" integer,
  "max_rpm" integer,
  "max_airflow_cfm" float,
  "static_pressure" float,
  "connector" varchar,
  "rgb" boolean
);

CREATE TABLE "watercooling_cpu_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "socket_support" varchar,
  "pump_speed_rpm" integer,
  "rgb" boolean
);

CREATE TABLE "aio_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "radiator_size_mm" integer,
  "fan_count" integer,
  "fan_size_mm" integer,
  "socket_support" varchar,
  "tubing_length_mm" integer,
  "rgb" boolean
);

CREATE TABLE "radiator_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "size_mm" integer,
  "thickness_mm" integer,
  "fan_slots" integer,
  "fan_size_mm" integer,
  "material" varchar
);

CREATE TABLE "gpu_watercooling_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "compatible_gpus" varchar,
  "material" varchar,
  "rgb" boolean
);

CREATE TABLE "fitting_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "type" varchar,
  "thread" varchar,
  "material" varchar,
  "color" varchar
);

CREATE TABLE "tubing_specs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" integer,
  "type" varchar,
  "inner_diameter_mm" float,
  "outer_diameter_mm" float,
  "material" varchar,
  "length_m" float,
  "color" varchar
);

ALTER TABLE "subcategory" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product" ADD FOREIGN KEY ("category_id") REFERENCES "category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product" ADD FOREIGN KEY ("subcategory_id") REFERENCES "subcategory" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "price" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "price" ADD FOREIGN KEY ("shop_id") REFERENCES "shop" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gpu_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cpu_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mainboard_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "psu_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ram_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "storage_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "air_cooler_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "case_fan_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "watercooling_cpu_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "aio_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "radiator_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "gpu_watercooling_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "fitting_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tubing_specs" ADD FOREIGN KEY ("product_id") REFERENCES "product" ("id") DEFERRABLE INITIALLY IMMEDIATE;
